### ISSUE TITLE
test environment and three scripts on Windows

### ISSUE THREAD

**Issue by JohnVolk** [cpearson1/etr-biascorrect#4]
Would be good to test running new scripts on Windows, starting with activating the environment:

```shell
conda env create -f environment.yml
activate etr_bias
```

next run the following scripts in order:
```shell
# create CSV with station/gridMET pairs from station metadata 
python prep_input.py -i ETrBias_DataPackage/Station_Data.txt -g gridmet_cell_data.csv
# download gridMET time series that overlap stations, 2 yrs
python download_gridmet_ee.py -i merged_input.csv -o test_gridmet_data -y 2000-2001
# calculate monthly bias ratios
python calc_bias_ratios.py -i merged_input.csv -o test_ratios
```

The final result should be a series of files in the ``test_ratios`` directory containing the monthly 
bias ratios for each of the four stations in ``ETrBias_DataPackage/Station_Data.txt``.

**Comment by cpearson1** [comment]
I got the following resolve package error when trying to create the new environment:
![image](https://user-images.githubusercontent.com/14983120/50847600-de410980-1326-11e9-81e7-1aeb2c2f6714.png)

**Comment by JohnVolk** [comment]
Thanks, yea looks like there a lot of issues with the geospatial modules on Windows (from what I have been reading), it was hard enough to get everything worked out on Linux. Mainly there are some issues with the current versions of Shapely and Fiona that require a lot of dependencies and downgrades on some other packages as well as using the conda-forge channel as opposed to defaults. One way around this is to simply make two environment files, one for Windows and one for Linux/Unix which may work on Mac.
